Fixed AtlasProject for Atlas deployment chart
mongodb/helm-charts pull request #216
Opened 2023-03-30 19:04 UTC by igor-karpukhin

### All Submissions:

* [ ] Have you opened an Issue before filing this PR?
* [x] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [ ] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

2023-03-30 19:43 UTC, igor-karpukhin commented on charts/atlas-deployment/values.yaml
> -    - ipAddress: "0.0.0.0/1"
Maybe you talking about the `CIDRBlock`?

2023-04-14 14:46 UTC, helderjs requested changes

2023-07-03 09:54 UTC, igor-karpukhin commented on charts/atlas-deployment/values.yaml
> -    - ipAddress: "0.0.0.0/1"
You can try to create a project with the `projectIpAccessList.ipAddress = "0.0.0.0"` it works

2023-10-03 10:51 UTC, josvazg approved these changes

2023-10-20 08:06 UTC, josvazg commented
Any concern why this has not been merged yet?

2023-10-20 09:49 UTC, helderjs approved these changes

2023-10-20 09:49 UTC, merged