[community-operator] Add support of securityContext for operator pod and container
mongodb/helm-charts pull request #237
Opened 2023-06-28 13:40 UTC by legal90

Closes #236

This PR adds two variables which allow to customize securityContext:
- `operator.securityContext`  (for the container level)
- `operator.podSecurityContext`  (for the pod level) 

These vars have default values, which are backward compatible with previous behavior: both `readOnlyRootFilesystem: true` and `runAsUser: 2000`. New values added by default do not break the functionality and only improve the security posture of the operator pod in runtime.

Ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

### All Submissions:

* [x] Have you opened an Issue before filing this PR?
* [x] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

2023-07-05 13:33 UTC, slaskawi requested changes
One small change is required. Apart from that - LGTM

2023-07-06 12:45 UTC, legal90 commented on charts/community-operator/values.yaml
> +    capabilities:
Thank you for the review, @slaskawi! 
I changed the default value of `operator. securityContext` to the empty map now 👍

2023-07-10 13:01 UTC, slaskawi approved these changes

2023-07-10 13:20 UTC, mircea-cosbuc approved these changes
LGTM!

2023-07-10 13:22 UTC, merged

2023-07-10 13:22 UTC, slaskawi commented
Thanks for the contribution @legal90 !

2023-07-17 06:15 UTC, legal90 commented
@slaskawi Thank you! Could you please release a new version of the `community-operator` chart with this PR included?